# Generated by Django 6.0.2 on 2026-02-20 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructureComponentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'FIXED'), ('PERCENT', 'PERCENT'), ('FORMULA', 'FORMULA')], max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(blank=True, db_column='formula_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_mappings', to='payroll.payrollformula')),
                ('salary_component', models.ForeignKey(db_column='salary_component_id', on_delete=django.db.models.deletion.CASCADE, related_name='structure_mappings', to='payroll.salarycomponent')),
                ('salary_structure_version', models.ForeignKey(db_column='salary_structure_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='component_mappings', to='payroll.salarystructureversion')),
            ],
            options={
                'db_table': 'salary_structure_component_mappings',
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('salary_structure_version', 'salary_component')},
            },
        ),
    ]
