# Generated by Django 6.0.2 on 2026-02-19 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("legal_name", models.CharField(max_length=200)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("pan_number", models.CharField(blank=True, max_length=20, null=True)),
                ("tan_number", models.CharField(blank=True, max_length=20, null=True)),
                ("pf_number", models.CharField(blank=True, max_length=50, null=True)),
                ("esi_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "professional_tax_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("timezone", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "companies",
                "indexes": [
                    models.Index(fields=["name"], name="companies_name_c7a1b3_idx"),
                    models.Index(
                        fields=["is_active"], name="companies_is_acti_e9a12b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("financial_year_start_month", models.IntegerField()),
                ("payroll_cycle", models.CharField(max_length=50)),
                ("pf_enabled", models.BooleanField(default=True)),
                ("esi_enabled", models.BooleanField(default=True)),
                ("professional_tax_enabled", models.BooleanField(default=True)),
                ("tds_enabled", models.BooleanField(default=True)),
                ("attendance_enabled", models.BooleanField(default=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_settings",
            },
        ),
    ]
