# Generated by Django 6.0.2 on 2026-02-19 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year_start_month", models.IntegerField(default=4)),
                ("payroll_cycle", models.CharField(default="Monthly", max_length=50)),
                ("pf_enabled", models.BooleanField(default=False)),
                ("esi_enabled", models.BooleanField(default=False)),
                ("professional_tax_enabled", models.BooleanField(default=False)),
                ("tds_enabled", models.BooleanField(default=False)),
                ("attendance_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Settings",
                "db_table": "company_settings",
            },
        ),
    ]
