# Generated by Django 6.0.2 on 2026-02-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_companysettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="companies_name_c7a1b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="companies_is_acti_e9a12b_idx",
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="company",
            name="esi_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="pan_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="company",
            name="pf_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="professional_tax_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="registration_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="tan_number",
            field=models.CharField(max_length=20),
        ),
    ]
