# Generated by Django 6.0.2 on 2026-02-19 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('name', models.CharField(max_length=150)),
                ('component_type', models.CharField(choices=[('EARNING', 'EARNING'), ('DEDUCTION', 'DEDUCTION'), ('CONTRIBUTION', 'CONTRIBUTION')], max_length=20)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_pf_applicable', models.BooleanField(default=False)),
                ('is_esi_applicable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('company_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='salary.salarystructure')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'FIXED'), ('PERCENTAGE', 'PERCENTAGE')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salarycomponent')),
                ('salary_structure_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='salary.salarystructureversion')),
            ],
        ),
    ]
