# Generated by Django 5.2.11 on 2026-02-25 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working_days', models.IntegerField()),
                ('present_days', models.IntegerField()),
                ('leave_days', models.IntegerField()),
                ('lop_days', models.IntegerField()),
                ('payable_days', models.IntegerField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'payroll_items',
            },
        ),
        migrations.CreateModel(
            name='PayrollItemComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=150)),
                ('component_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'payroll_item_components',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payslip_number', models.CharField(max_length=150, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payslips',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_employees', models.IntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='companies.company')),
            ],
            options={
                'db_table': 'payrolls',
            },
        ),
    ]
