# Generated by Django 5.2.11 on 2026-02-25 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payroll'),
        ),
        migrations.AddField(
            model_name='payrollitemcomponent',
            name='payroll_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.payrollitem'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payrollitem'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('company', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollitem',
            unique_together={('payroll', 'employee')},
        ),
    ]
