# Generated by Django 6.0.2 on 2026-02-20 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_options_and_more"),
        ("employees", "0001_initial"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="generated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_payrolls",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_deductions",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_employees",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="leave_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="lop_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="paid_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="payable_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="present_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="total_deductions",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="payrollitem",
            name="working_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(default="Draft", max_length=50),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_gross",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_net",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollitem",
            name="gross_salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="payrollitem",
            name="net_salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name="EmployeeSalaryStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structure",
                        to="employees.employee",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "db_table": "employee_salary_structures",
            },
        ),
        migrations.CreateModel(
            name="PayrollFormula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("formula_expression", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_formulas",
            },
        ),
        migrations.CreateModel(
            name="PayrollItemComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("component_name", models.CharField(max_length=150)),
                ("component_type", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "payroll_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="payroll.payrollitem",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_item_components",
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payslip_number",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "payroll_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslip",
                        to="payroll.payrollitem",
                    ),
                ),
            ],
            options={
                "db_table": "payslips",
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("component_type", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("formula", models.TextField(blank=True, null=True)),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "db_table": "salary_structure_components",
            },
        ),
    ]
