# Generated by Django 5.2.11 on 2026-02-25 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollFormula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('formula_expression', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_formulas', to='companies.company')),
            ],
            options={
                'db_table': 'payroll_formulas',
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('component_type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], max_length=50)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_pf_applicable', models.BooleanField(default=False)),
                ('is_esi_applicable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='companies.company')),
            ],
            options={
                'db_table': 'salary_components',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='companies.company')),
            ],
            options={
                'db_table': 'salary_structures',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='payroll_formulas.salarystructure')),
            ],
            options={
                'db_table': 'salary_structure_versions',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureComponentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_type', models.CharField(default='Fixed', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_mappings', to='payroll_formulas.payrollformula')),
                ('salary_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_mappings', to='payroll_formulas.salarycomponent')),
                ('salary_structure_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_mappings', to='payroll_formulas.salarystructureversion')),
            ],
            options={
                'db_table': 'salary_structure_component_mappings',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignments', to='employees.employee')),
                ('salary_structure_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salaries', to='payroll_formulas.salarystructureversion')),
            ],
            options={
                'db_table': 'employee_salaries',
            },
        ),
    ]
